# site configuration

lang: en

# jekyll-seo-tag settings â€º https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# main title
title: Para TT Rankings Archive

github:
  username: gmarziou

# global switch for TOC in posts (boolean)
toc: false

